// Package models contains generated code for schema 'public'.
package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// AllPrinting represents a row from 'public.all_printings'.
type AllPrinting struct {
	ID      int            `json:"id"`       // id
	SetCode sql.NullString `json:"set_code"` // set_code
	SetData []byte         `json:"set_data"` // set_data
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [AllPrinting] exists in the database.
func (ap *AllPrinting) Exists() bool {
	return ap._exists
}

// Deleted returns true when the [AllPrinting] has been marked for deletion
// from the database.
func (ap *AllPrinting) Deleted() bool {
	return ap._deleted
}

// Insert inserts the [AllPrinting] to the database.
func (ap *AllPrinting) Insert(ctx context.Context, db DB) error {
	switch {
	case ap._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case ap._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.all_printings (` +
		`set_code, set_data` +
		`) VALUES (` +
		`$1, $2` +
		`) RETURNING id`
	// run
	logf(sqlstr, ap.SetCode, ap.SetData)
	if err := db.QueryRowContext(ctx, sqlstr, ap.SetCode, ap.SetData).Scan(&ap.ID); err != nil {
		return logerror(err)
	}
	// set exists
	ap._exists = true
	return nil
}

// Update updates a [AllPrinting] in the database.
func (ap *AllPrinting) Update(ctx context.Context, db DB) error {
	switch {
	case !ap._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case ap._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.all_printings SET ` +
		`set_code = $1, set_data = $2 ` +
		`WHERE id = $3`
	// run
	logf(sqlstr, ap.SetCode, ap.SetData, ap.ID)
	if _, err := db.ExecContext(ctx, sqlstr, ap.SetCode, ap.SetData, ap.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [AllPrinting] to the database.
func (ap *AllPrinting) Save(ctx context.Context, db DB) error {
	if ap.Exists() {
		return ap.Update(ctx, db)
	}
	return ap.Insert(ctx, db)
}

// Upsert performs an upsert for [AllPrinting].
func (ap *AllPrinting) Upsert(ctx context.Context, db DB) error {
	switch {
	case ap._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.all_printings (` +
		`id, set_code, set_data` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`set_code = EXCLUDED.set_code, set_data = EXCLUDED.set_data `
	// run
	logf(sqlstr, ap.ID, ap.SetCode, ap.SetData)
	if _, err := db.ExecContext(ctx, sqlstr, ap.ID, ap.SetCode, ap.SetData); err != nil {
		return logerror(err)
	}
	// set exists
	ap._exists = true
	return nil
}

// Delete deletes the [AllPrinting] from the database.
func (ap *AllPrinting) Delete(ctx context.Context, db DB) error {
	switch {
	case !ap._exists: // doesn't exist
		return nil
	case ap._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.all_printings ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, ap.ID)
	if _, err := db.ExecContext(ctx, sqlstr, ap.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	ap._deleted = true
	return nil
}

// AllPrintingByID retrieves a row from 'public.all_printings' as a [AllPrinting].
//
// Generated from index 'all_printings_pkey'.
func AllPrintingByID(ctx context.Context, db DB, id int) (*AllPrinting, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, set_code, set_data ` +
		`FROM public.all_printings ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	ap := AllPrinting{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&ap.ID, &ap.SetCode, &ap.SetData); err != nil {
		return nil, logerror(err)
	}
	return &ap, nil
}
