package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Cardidentifier represents a row from 'public.cardidentifiers'.
type Cardidentifier struct {
	ID                       int            `json:"id"`                       // id
	Cardkingdometchedid      sql.NullString `json:"cardkingdometchedid"`      // cardkingdometchedid
	Cardkingdomfoilid        sql.NullString `json:"cardkingdomfoilid"`        // cardkingdomfoilid
	Cardkingdomid            sql.NullString `json:"cardkingdomid"`            // cardkingdomid
	Cardspherefoilid         sql.NullString `json:"cardspherefoilid"`         // cardspherefoilid
	Cardsphereid             sql.NullString `json:"cardsphereid"`             // cardsphereid
	Deckboxid                sql.NullString `json:"deckboxid"`                // deckboxid
	Mcmid                    sql.NullString `json:"mcmid"`                    // mcmid
	Mcmmetaid                sql.NullString `json:"mcmmetaid"`                // mcmmetaid
	Mtgarenaid               sql.NullString `json:"mtgarenaid"`               // mtgarenaid
	Mtgjsonfoilversionid     sql.NullString `json:"mtgjsonfoilversionid"`     // mtgjsonfoilversionid
	Mtgjsonnonfoilversionid  sql.NullString `json:"mtgjsonnonfoilversionid"`  // mtgjsonnonfoilversionid
	Mtgjsonv4id              sql.NullString `json:"mtgjsonv4id"`              // mtgjsonv4id
	Mtgofoilid               sql.NullString `json:"mtgofoilid"`               // mtgofoilid
	Mtgoid                   sql.NullString `json:"mtgoid"`                   // mtgoid
	Multiverseid             sql.NullString `json:"multiverseid"`             // multiverseid
	Scryfallcardbackid       sql.NullString `json:"scryfallcardbackid"`       // scryfallcardbackid
	Scryfallid               sql.NullString `json:"scryfallid"`               // scryfallid
	Scryfallillustrationid   sql.NullString `json:"scryfallillustrationid"`   // scryfallillustrationid
	Scryfalloracleid         sql.NullString `json:"scryfalloracleid"`         // scryfalloracleid
	Tcgplayeretchedproductid sql.NullString `json:"tcgplayeretchedproductid"` // tcgplayeretchedproductid
	Tcgplayerproductid       sql.NullString `json:"tcgplayerproductid"`       // tcgplayerproductid
	UUID                     sql.NullString `json:"uuid"`                     // uuid
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Cardidentifier] exists in the database.
func (c *Cardidentifier) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Cardidentifier] has been marked for deletion
// from the database.
func (c *Cardidentifier) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Cardidentifier] to the database.
func (c *Cardidentifier) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.cardidentifiers (` +
		`cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22` +
		`) RETURNING id`
	// run
	logf(sqlstr, c.Cardkingdometchedid, c.Cardkingdomfoilid, c.Cardkingdomid, c.Cardspherefoilid, c.Cardsphereid, c.Deckboxid, c.Mcmid, c.Mcmmetaid, c.Mtgarenaid, c.Mtgjsonfoilversionid, c.Mtgjsonnonfoilversionid, c.Mtgjsonv4id, c.Mtgofoilid, c.Mtgoid, c.Multiverseid, c.Scryfallcardbackid, c.Scryfallid, c.Scryfallillustrationid, c.Scryfalloracleid, c.Tcgplayeretchedproductid, c.Tcgplayerproductid, c.UUID)
	if err := db.QueryRowContext(ctx, sqlstr, c.Cardkingdometchedid, c.Cardkingdomfoilid, c.Cardkingdomid, c.Cardspherefoilid, c.Cardsphereid, c.Deckboxid, c.Mcmid, c.Mcmmetaid, c.Mtgarenaid, c.Mtgjsonfoilversionid, c.Mtgjsonnonfoilversionid, c.Mtgjsonv4id, c.Mtgofoilid, c.Mtgoid, c.Multiverseid, c.Scryfallcardbackid, c.Scryfallid, c.Scryfallillustrationid, c.Scryfalloracleid, c.Tcgplayeretchedproductid, c.Tcgplayerproductid, c.UUID).Scan(&c.ID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Cardidentifier] in the database.
func (c *Cardidentifier) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.cardidentifiers SET ` +
		`cardkingdometchedid = $1, cardkingdomfoilid = $2, cardkingdomid = $3, cardspherefoilid = $4, cardsphereid = $5, deckboxid = $6, mcmid = $7, mcmmetaid = $8, mtgarenaid = $9, mtgjsonfoilversionid = $10, mtgjsonnonfoilversionid = $11, mtgjsonv4id = $12, mtgofoilid = $13, mtgoid = $14, multiverseid = $15, scryfallcardbackid = $16, scryfallid = $17, scryfallillustrationid = $18, scryfalloracleid = $19, tcgplayeretchedproductid = $20, tcgplayerproductid = $21, uuid = $22 ` +
		`WHERE id = $23`
	// run
	logf(sqlstr, c.Cardkingdometchedid, c.Cardkingdomfoilid, c.Cardkingdomid, c.Cardspherefoilid, c.Cardsphereid, c.Deckboxid, c.Mcmid, c.Mcmmetaid, c.Mtgarenaid, c.Mtgjsonfoilversionid, c.Mtgjsonnonfoilversionid, c.Mtgjsonv4id, c.Mtgofoilid, c.Mtgoid, c.Multiverseid, c.Scryfallcardbackid, c.Scryfallid, c.Scryfallillustrationid, c.Scryfalloracleid, c.Tcgplayeretchedproductid, c.Tcgplayerproductid, c.UUID, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.Cardkingdometchedid, c.Cardkingdomfoilid, c.Cardkingdomid, c.Cardspherefoilid, c.Cardsphereid, c.Deckboxid, c.Mcmid, c.Mcmmetaid, c.Mtgarenaid, c.Mtgjsonfoilversionid, c.Mtgjsonnonfoilversionid, c.Mtgjsonv4id, c.Mtgofoilid, c.Mtgoid, c.Multiverseid, c.Scryfallcardbackid, c.Scryfallid, c.Scryfallillustrationid, c.Scryfalloracleid, c.Tcgplayeretchedproductid, c.Tcgplayerproductid, c.UUID, c.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Cardidentifier] to the database.
func (c *Cardidentifier) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Cardidentifier].
func (c *Cardidentifier) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.cardidentifiers (` +
		`id, cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`cardkingdometchedid = EXCLUDED.cardkingdometchedid, cardkingdomfoilid = EXCLUDED.cardkingdomfoilid, cardkingdomid = EXCLUDED.cardkingdomid, cardspherefoilid = EXCLUDED.cardspherefoilid, cardsphereid = EXCLUDED.cardsphereid, deckboxid = EXCLUDED.deckboxid, mcmid = EXCLUDED.mcmid, mcmmetaid = EXCLUDED.mcmmetaid, mtgarenaid = EXCLUDED.mtgarenaid, mtgjsonfoilversionid = EXCLUDED.mtgjsonfoilversionid, mtgjsonnonfoilversionid = EXCLUDED.mtgjsonnonfoilversionid, mtgjsonv4id = EXCLUDED.mtgjsonv4id, mtgofoilid = EXCLUDED.mtgofoilid, mtgoid = EXCLUDED.mtgoid, multiverseid = EXCLUDED.multiverseid, scryfallcardbackid = EXCLUDED.scryfallcardbackid, scryfallid = EXCLUDED.scryfallid, scryfallillustrationid = EXCLUDED.scryfallillustrationid, scryfalloracleid = EXCLUDED.scryfalloracleid, tcgplayeretchedproductid = EXCLUDED.tcgplayeretchedproductid, tcgplayerproductid = EXCLUDED.tcgplayerproductid, uuid = EXCLUDED.uuid `
	// run
	logf(sqlstr, c.ID, c.Cardkingdometchedid, c.Cardkingdomfoilid, c.Cardkingdomid, c.Cardspherefoilid, c.Cardsphereid, c.Deckboxid, c.Mcmid, c.Mcmmetaid, c.Mtgarenaid, c.Mtgjsonfoilversionid, c.Mtgjsonnonfoilversionid, c.Mtgjsonv4id, c.Mtgofoilid, c.Mtgoid, c.Multiverseid, c.Scryfallcardbackid, c.Scryfallid, c.Scryfallillustrationid, c.Scryfalloracleid, c.Tcgplayeretchedproductid, c.Tcgplayerproductid, c.UUID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Cardkingdometchedid, c.Cardkingdomfoilid, c.Cardkingdomid, c.Cardspherefoilid, c.Cardsphereid, c.Deckboxid, c.Mcmid, c.Mcmmetaid, c.Mtgarenaid, c.Mtgjsonfoilversionid, c.Mtgjsonnonfoilversionid, c.Mtgjsonv4id, c.Mtgofoilid, c.Mtgoid, c.Multiverseid, c.Scryfallcardbackid, c.Scryfallid, c.Scryfallillustrationid, c.Scryfalloracleid, c.Tcgplayeretchedproductid, c.Tcgplayerproductid, c.UUID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Cardidentifier] from the database.
func (c *Cardidentifier) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.cardidentifiers ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CardidentifierByID retrieves a row from 'public.cardidentifiers' as a [Cardidentifier].
//
// Generated from index 'cardidentifiers_pkey'.
func CardidentifierByID(ctx context.Context, db DB, id int) (*Cardidentifier, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid ` +
		`FROM public.cardidentifiers ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	c := Cardidentifier{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&c.ID, &c.Cardkingdometchedid, &c.Cardkingdomfoilid, &c.Cardkingdomid, &c.Cardspherefoilid, &c.Cardsphereid, &c.Deckboxid, &c.Mcmid, &c.Mcmmetaid, &c.Mtgarenaid, &c.Mtgjsonfoilversionid, &c.Mtgjsonnonfoilversionid, &c.Mtgjsonv4id, &c.Mtgofoilid, &c.Mtgoid, &c.Multiverseid, &c.Scryfallcardbackid, &c.Scryfallid, &c.Scryfallillustrationid, &c.Scryfalloracleid, &c.Tcgplayeretchedproductid, &c.Tcgplayerproductid, &c.UUID); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CardidentifiersByUUID retrieves a row from 'public.cardidentifiers' as a [Cardidentifier].
//
// Generated from index 'cardidentifiers_uuid'.
func CardidentifiersByUUID(ctx context.Context, db DB, uuid sql.NullString) ([]*Cardidentifier, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid ` +
		`FROM public.cardidentifiers ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Cardidentifier
	for rows.Next() {
		c := Cardidentifier{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.ID, &c.Cardkingdometchedid, &c.Cardkingdomfoilid, &c.Cardkingdomid, &c.Cardspherefoilid, &c.Cardsphereid, &c.Deckboxid, &c.Mcmid, &c.Mcmmetaid, &c.Mtgarenaid, &c.Mtgjsonfoilversionid, &c.Mtgjsonnonfoilversionid, &c.Mtgjsonv4id, &c.Mtgofoilid, &c.Mtgoid, &c.Multiverseid, &c.Scryfallcardbackid, &c.Scryfallid, &c.Scryfallillustrationid, &c.Scryfalloracleid, &c.Tcgplayeretchedproductid, &c.Tcgplayerproductid, &c.UUID); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
