package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Cardruling represents a row from 'public.cardrulings'.
type Cardruling struct {
	ID   int            `json:"id"`   // id
	Date sql.NullTime   `json:"date"` // date
	Text sql.NullString `json:"text"` // text
	UUID string         `json:"uuid"` // uuid
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Cardruling] exists in the database.
func (c *Cardruling) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Cardruling] has been marked for deletion
// from the database.
func (c *Cardruling) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Cardruling] to the database.
func (c *Cardruling) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.cardrulings (` +
		`date, text, uuid` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) RETURNING id`
	// run
	logf(sqlstr, c.Date, c.Text, c.UUID)
	if err := db.QueryRowContext(ctx, sqlstr, c.Date, c.Text, c.UUID).Scan(&c.ID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Cardruling] in the database.
func (c *Cardruling) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.cardrulings SET ` +
		`date = $1, text = $2, uuid = $3 ` +
		`WHERE id = $4`
	// run
	logf(sqlstr, c.Date, c.Text, c.UUID, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.Date, c.Text, c.UUID, c.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Cardruling] to the database.
func (c *Cardruling) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Cardruling].
func (c *Cardruling) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.cardrulings (` +
		`id, date, text, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`date = EXCLUDED.date, text = EXCLUDED.text, uuid = EXCLUDED.uuid `
	// run
	logf(sqlstr, c.ID, c.Date, c.Text, c.UUID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Date, c.Text, c.UUID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Cardruling] from the database.
func (c *Cardruling) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.cardrulings ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CardrulingByID retrieves a row from 'public.cardrulings' as a [Cardruling].
//
// Generated from index 'cardrulings_pkey'.
func CardrulingByID(ctx context.Context, db DB, id int) (*Cardruling, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, date, text, uuid ` +
		`FROM public.cardrulings ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	c := Cardruling{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&c.ID, &c.Date, &c.Text, &c.UUID); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CardrulingsByUUID retrieves a row from 'public.cardrulings' as a [Cardruling].
//
// Generated from index 'cardrulings_uuid'.
func CardrulingsByUUID(ctx context.Context, db DB, uuid string) ([]*Cardruling, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, date, text, uuid ` +
		`FROM public.cardrulings ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Cardruling
	for rows.Next() {
		c := Cardruling{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.ID, &c.Date, &c.Text, &c.UUID); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
