package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Cardforeigndatum represents a row from 'public.cardforeigndata'.
type Cardforeigndatum struct {
	ID           int            `json:"id"`           // id
	Facename     sql.NullString `json:"facename"`     // facename
	Flavortext   sql.NullString `json:"flavortext"`   // flavortext
	Identifiers  sql.NullString `json:"identifiers"`  // identifiers
	Language     sql.NullString `json:"language"`     // language
	Multiverseid sql.NullInt64  `json:"multiverseid"` // multiverseid
	Name         sql.NullString `json:"name"`         // name
	Text         sql.NullString `json:"text"`         // text
	Type         sql.NullString `json:"type"`         // type
	UUID         sql.NullString `json:"uuid"`         // uuid
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Cardforeigndatum] exists in the database.
func (c *Cardforeigndatum) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Cardforeigndatum] has been marked for deletion
// from the database.
func (c *Cardforeigndatum) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Cardforeigndatum] to the database.
func (c *Cardforeigndatum) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.cardforeigndata (` +
		`facename, flavortext, identifiers, language, multiverseid, name, text, type, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`) RETURNING id`
	// run
	logf(sqlstr, c.Facename, c.Flavortext, c.Identifiers, c.Language, c.Multiverseid, c.Name, c.Text, c.Type, c.UUID)
	if err := db.QueryRowContext(ctx, sqlstr, c.Facename, c.Flavortext, c.Identifiers, c.Language, c.Multiverseid, c.Name, c.Text, c.Type, c.UUID).Scan(&c.ID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Cardforeigndatum] in the database.
func (c *Cardforeigndatum) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.cardforeigndata SET ` +
		`facename = $1, flavortext = $2, identifiers = $3, language = $4, multiverseid = $5, name = $6, text = $7, type = $8, uuid = $9 ` +
		`WHERE id = $10`
	// run
	logf(sqlstr, c.Facename, c.Flavortext, c.Identifiers, c.Language, c.Multiverseid, c.Name, c.Text, c.Type, c.UUID, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.Facename, c.Flavortext, c.Identifiers, c.Language, c.Multiverseid, c.Name, c.Text, c.Type, c.UUID, c.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Cardforeigndatum] to the database.
func (c *Cardforeigndatum) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Cardforeigndatum].
func (c *Cardforeigndatum) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.cardforeigndata (` +
		`id, facename, flavortext, identifiers, language, multiverseid, name, text, type, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`facename = EXCLUDED.facename, flavortext = EXCLUDED.flavortext, identifiers = EXCLUDED.identifiers, language = EXCLUDED.language, multiverseid = EXCLUDED.multiverseid, name = EXCLUDED.name, text = EXCLUDED.text, type = EXCLUDED.type, uuid = EXCLUDED.uuid `
	// run
	logf(sqlstr, c.ID, c.Facename, c.Flavortext, c.Identifiers, c.Language, c.Multiverseid, c.Name, c.Text, c.Type, c.UUID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Facename, c.Flavortext, c.Identifiers, c.Language, c.Multiverseid, c.Name, c.Text, c.Type, c.UUID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Cardforeigndatum] from the database.
func (c *Cardforeigndatum) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.cardforeigndata ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CardforeigndatumByID retrieves a row from 'public.cardforeigndata' as a [Cardforeigndatum].
//
// Generated from index 'cardforeigndata_pkey'.
func CardforeigndatumByID(ctx context.Context, db DB, id int) (*Cardforeigndatum, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, facename, flavortext, identifiers, language, multiverseid, name, text, type, uuid ` +
		`FROM public.cardforeigndata ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	c := Cardforeigndatum{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&c.ID, &c.Facename, &c.Flavortext, &c.Identifiers, &c.Language, &c.Multiverseid, &c.Name, &c.Text, &c.Type, &c.UUID); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CardforeigndataByUUID retrieves a row from 'public.cardforeigndata' as a [Cardforeigndatum].
//
// Generated from index 'cardforeigndata_uuid'.
func CardforeigndataByUUID(ctx context.Context, db DB, uuid sql.NullString) ([]*Cardforeigndatum, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, facename, flavortext, identifiers, language, multiverseid, name, text, type, uuid ` +
		`FROM public.cardforeigndata ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Cardforeigndatum
	for rows.Next() {
		c := Cardforeigndatum{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.ID, &c.Facename, &c.Flavortext, &c.Identifiers, &c.Language, &c.Multiverseid, &c.Name, &c.Text, &c.Type, &c.UUID); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
