package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Cardpurchaseurl represents a row from 'public.cardpurchaseurls'.
type Cardpurchaseurl struct {
	ID                int            `json:"id"`                // id
	Cardkingdom       sql.NullString `json:"cardkingdom"`       // cardkingdom
	Cardkingdometched sql.NullString `json:"cardkingdometched"` // cardkingdometched
	Cardkingdomfoil   sql.NullString `json:"cardkingdomfoil"`   // cardkingdomfoil
	Cardmarket        sql.NullString `json:"cardmarket"`        // cardmarket
	Tcgplayer         sql.NullString `json:"tcgplayer"`         // tcgplayer
	Tcgplayeretched   sql.NullString `json:"tcgplayeretched"`   // tcgplayeretched
	UUID              sql.NullString `json:"uuid"`              // uuid
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Cardpurchaseurl] exists in the database.
func (c *Cardpurchaseurl) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Cardpurchaseurl] has been marked for deletion
// from the database.
func (c *Cardpurchaseurl) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Cardpurchaseurl] to the database.
func (c *Cardpurchaseurl) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.cardpurchaseurls (` +
		`cardkingdom, cardkingdometched, cardkingdomfoil, cardmarket, tcgplayer, tcgplayeretched, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7` +
		`) RETURNING id`
	// run
	logf(sqlstr, c.Cardkingdom, c.Cardkingdometched, c.Cardkingdomfoil, c.Cardmarket, c.Tcgplayer, c.Tcgplayeretched, c.UUID)
	if err := db.QueryRowContext(ctx, sqlstr, c.Cardkingdom, c.Cardkingdometched, c.Cardkingdomfoil, c.Cardmarket, c.Tcgplayer, c.Tcgplayeretched, c.UUID).Scan(&c.ID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Cardpurchaseurl] in the database.
func (c *Cardpurchaseurl) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.cardpurchaseurls SET ` +
		`cardkingdom = $1, cardkingdometched = $2, cardkingdomfoil = $3, cardmarket = $4, tcgplayer = $5, tcgplayeretched = $6, uuid = $7 ` +
		`WHERE id = $8`
	// run
	logf(sqlstr, c.Cardkingdom, c.Cardkingdometched, c.Cardkingdomfoil, c.Cardmarket, c.Tcgplayer, c.Tcgplayeretched, c.UUID, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.Cardkingdom, c.Cardkingdometched, c.Cardkingdomfoil, c.Cardmarket, c.Tcgplayer, c.Tcgplayeretched, c.UUID, c.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Cardpurchaseurl] to the database.
func (c *Cardpurchaseurl) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Cardpurchaseurl].
func (c *Cardpurchaseurl) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.cardpurchaseurls (` +
		`id, cardkingdom, cardkingdometched, cardkingdomfoil, cardmarket, tcgplayer, tcgplayeretched, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`cardkingdom = EXCLUDED.cardkingdom, cardkingdometched = EXCLUDED.cardkingdometched, cardkingdomfoil = EXCLUDED.cardkingdomfoil, cardmarket = EXCLUDED.cardmarket, tcgplayer = EXCLUDED.tcgplayer, tcgplayeretched = EXCLUDED.tcgplayeretched, uuid = EXCLUDED.uuid `
	// run
	logf(sqlstr, c.ID, c.Cardkingdom, c.Cardkingdometched, c.Cardkingdomfoil, c.Cardmarket, c.Tcgplayer, c.Tcgplayeretched, c.UUID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Cardkingdom, c.Cardkingdometched, c.Cardkingdomfoil, c.Cardmarket, c.Tcgplayer, c.Tcgplayeretched, c.UUID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Cardpurchaseurl] from the database.
func (c *Cardpurchaseurl) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.cardpurchaseurls ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CardpurchaseurlByID retrieves a row from 'public.cardpurchaseurls' as a [Cardpurchaseurl].
//
// Generated from index 'cardpurchaseurls_pkey'.
func CardpurchaseurlByID(ctx context.Context, db DB, id int) (*Cardpurchaseurl, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, cardkingdom, cardkingdometched, cardkingdomfoil, cardmarket, tcgplayer, tcgplayeretched, uuid ` +
		`FROM public.cardpurchaseurls ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	c := Cardpurchaseurl{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&c.ID, &c.Cardkingdom, &c.Cardkingdometched, &c.Cardkingdomfoil, &c.Cardmarket, &c.Tcgplayer, &c.Tcgplayeretched, &c.UUID); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CardpurchaseurlsByUUID retrieves a row from 'public.cardpurchaseurls' as a [Cardpurchaseurl].
//
// Generated from index 'cardpurchaseurls_uuid'.
func CardpurchaseurlsByUUID(ctx context.Context, db DB, uuid sql.NullString) ([]*Cardpurchaseurl, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, cardkingdom, cardkingdometched, cardkingdomfoil, cardmarket, tcgplayer, tcgplayeretched, uuid ` +
		`FROM public.cardpurchaseurls ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Cardpurchaseurl
	for rows.Next() {
		c := Cardpurchaseurl{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.ID, &c.Cardkingdom, &c.Cardkingdometched, &c.Cardkingdomfoil, &c.Cardmarket, &c.Tcgplayer, &c.Tcgplayeretched, &c.UUID); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
