package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Cardlegality represents a row from 'public.cardlegalities'.
type Cardlegality struct {
	ID              int            `json:"id"`              // id
	Alchemy         sql.NullString `json:"alchemy"`         // alchemy
	Brawl           sql.NullString `json:"brawl"`           // brawl
	Commander       sql.NullString `json:"commander"`       // commander
	Duel            sql.NullString `json:"duel"`            // duel
	Future          sql.NullString `json:"future"`          // future
	Gladiator       sql.NullString `json:"gladiator"`       // gladiator
	Historic        sql.NullString `json:"historic"`        // historic
	Legacy          sql.NullString `json:"legacy"`          // legacy
	Modern          sql.NullString `json:"modern"`          // modern
	Oathbreaker     sql.NullString `json:"oathbreaker"`     // oathbreaker
	Oldschool       sql.NullString `json:"oldschool"`       // oldschool
	Pauper          sql.NullString `json:"pauper"`          // pauper
	Paupercommander sql.NullString `json:"paupercommander"` // paupercommander
	Penny           sql.NullString `json:"penny"`           // penny
	Pioneer         sql.NullString `json:"pioneer"`         // pioneer
	Predh           sql.NullString `json:"predh"`           // predh
	Premodern       sql.NullString `json:"premodern"`       // premodern
	Standard        sql.NullString `json:"standard"`        // standard
	Standardbrawl   sql.NullString `json:"standardbrawl"`   // standardbrawl
	Timeless        sql.NullString `json:"timeless"`        // timeless
	UUID            sql.NullString `json:"uuid"`            // uuid
	Vintage         sql.NullString `json:"vintage"`         // vintage
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Cardlegality] exists in the database.
func (c *Cardlegality) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Cardlegality] has been marked for deletion
// from the database.
func (c *Cardlegality) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Cardlegality] to the database.
func (c *Cardlegality) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.cardlegalities (` +
		`alchemy, brawl, commander, duel, future, gladiator, historic, legacy, modern, oathbreaker, oldschool, pauper, paupercommander, penny, pioneer, predh, premodern, standard, standardbrawl, timeless, uuid, vintage` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22` +
		`) RETURNING id`
	// run
	logf(sqlstr, c.Alchemy, c.Brawl, c.Commander, c.Duel, c.Future, c.Gladiator, c.Historic, c.Legacy, c.Modern, c.Oathbreaker, c.Oldschool, c.Pauper, c.Paupercommander, c.Penny, c.Pioneer, c.Predh, c.Premodern, c.Standard, c.Standardbrawl, c.Timeless, c.UUID, c.Vintage)
	if err := db.QueryRowContext(ctx, sqlstr, c.Alchemy, c.Brawl, c.Commander, c.Duel, c.Future, c.Gladiator, c.Historic, c.Legacy, c.Modern, c.Oathbreaker, c.Oldschool, c.Pauper, c.Paupercommander, c.Penny, c.Pioneer, c.Predh, c.Premodern, c.Standard, c.Standardbrawl, c.Timeless, c.UUID, c.Vintage).Scan(&c.ID); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Cardlegality] in the database.
func (c *Cardlegality) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.cardlegalities SET ` +
		`alchemy = $1, brawl = $2, commander = $3, duel = $4, future = $5, gladiator = $6, historic = $7, legacy = $8, modern = $9, oathbreaker = $10, oldschool = $11, pauper = $12, paupercommander = $13, penny = $14, pioneer = $15, predh = $16, premodern = $17, standard = $18, standardbrawl = $19, timeless = $20, uuid = $21, vintage = $22 ` +
		`WHERE id = $23`
	// run
	logf(sqlstr, c.Alchemy, c.Brawl, c.Commander, c.Duel, c.Future, c.Gladiator, c.Historic, c.Legacy, c.Modern, c.Oathbreaker, c.Oldschool, c.Pauper, c.Paupercommander, c.Penny, c.Pioneer, c.Predh, c.Premodern, c.Standard, c.Standardbrawl, c.Timeless, c.UUID, c.Vintage, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.Alchemy, c.Brawl, c.Commander, c.Duel, c.Future, c.Gladiator, c.Historic, c.Legacy, c.Modern, c.Oathbreaker, c.Oldschool, c.Pauper, c.Paupercommander, c.Penny, c.Pioneer, c.Predh, c.Premodern, c.Standard, c.Standardbrawl, c.Timeless, c.UUID, c.Vintage, c.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Cardlegality] to the database.
func (c *Cardlegality) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Cardlegality].
func (c *Cardlegality) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.cardlegalities (` +
		`id, alchemy, brawl, commander, duel, future, gladiator, historic, legacy, modern, oathbreaker, oldschool, pauper, paupercommander, penny, pioneer, predh, premodern, standard, standardbrawl, timeless, uuid, vintage` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`alchemy = EXCLUDED.alchemy, brawl = EXCLUDED.brawl, commander = EXCLUDED.commander, duel = EXCLUDED.duel, future = EXCLUDED.future, gladiator = EXCLUDED.gladiator, historic = EXCLUDED.historic, legacy = EXCLUDED.legacy, modern = EXCLUDED.modern, oathbreaker = EXCLUDED.oathbreaker, oldschool = EXCLUDED.oldschool, pauper = EXCLUDED.pauper, paupercommander = EXCLUDED.paupercommander, penny = EXCLUDED.penny, pioneer = EXCLUDED.pioneer, predh = EXCLUDED.predh, premodern = EXCLUDED.premodern, standard = EXCLUDED.standard, standardbrawl = EXCLUDED.standardbrawl, timeless = EXCLUDED.timeless, uuid = EXCLUDED.uuid, vintage = EXCLUDED.vintage `
	// run
	logf(sqlstr, c.ID, c.Alchemy, c.Brawl, c.Commander, c.Duel, c.Future, c.Gladiator, c.Historic, c.Legacy, c.Modern, c.Oathbreaker, c.Oldschool, c.Pauper, c.Paupercommander, c.Penny, c.Pioneer, c.Predh, c.Premodern, c.Standard, c.Standardbrawl, c.Timeless, c.UUID, c.Vintage)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Alchemy, c.Brawl, c.Commander, c.Duel, c.Future, c.Gladiator, c.Historic, c.Legacy, c.Modern, c.Oathbreaker, c.Oldschool, c.Pauper, c.Paupercommander, c.Penny, c.Pioneer, c.Predh, c.Premodern, c.Standard, c.Standardbrawl, c.Timeless, c.UUID, c.Vintage); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Cardlegality] from the database.
func (c *Cardlegality) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.cardlegalities ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CardlegalityByID retrieves a row from 'public.cardlegalities' as a [Cardlegality].
//
// Generated from index 'cardlegalities_pkey'.
func CardlegalityByID(ctx context.Context, db DB, id int) (*Cardlegality, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, alchemy, brawl, commander, duel, future, gladiator, historic, legacy, modern, oathbreaker, oldschool, pauper, paupercommander, penny, pioneer, predh, premodern, standard, standardbrawl, timeless, uuid, vintage ` +
		`FROM public.cardlegalities ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	c := Cardlegality{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&c.ID, &c.Alchemy, &c.Brawl, &c.Commander, &c.Duel, &c.Future, &c.Gladiator, &c.Historic, &c.Legacy, &c.Modern, &c.Oathbreaker, &c.Oldschool, &c.Pauper, &c.Paupercommander, &c.Penny, &c.Pioneer, &c.Predh, &c.Premodern, &c.Standard, &c.Standardbrawl, &c.Timeless, &c.UUID, &c.Vintage); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CardlegalitiesByUUID retrieves a row from 'public.cardlegalities' as a [Cardlegality].
//
// Generated from index 'cardlegalities_uuid'.
func CardlegalitiesByUUID(ctx context.Context, db DB, uuid sql.NullString) ([]*Cardlegality, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, alchemy, brawl, commander, duel, future, gladiator, historic, legacy, modern, oathbreaker, oldschool, pauper, paupercommander, penny, pioneer, predh, premodern, standard, standardbrawl, timeless, uuid, vintage ` +
		`FROM public.cardlegalities ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Cardlegality
	for rows.Next() {
		c := Cardlegality{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&c.ID, &c.Alchemy, &c.Brawl, &c.Commander, &c.Duel, &c.Future, &c.Gladiator, &c.Historic, &c.Legacy, &c.Modern, &c.Oathbreaker, &c.Oldschool, &c.Pauper, &c.Paupercommander, &c.Penny, &c.Pioneer, &c.Predh, &c.Premodern, &c.Standard, &c.Standardbrawl, &c.Timeless, &c.UUID, &c.Vintage); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
