package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Metum represents a row from 'public.meta'.
type Metum struct {
	ID      int            `json:"id"`      // id
	Date    sql.NullTime   `json:"date"`    // date
	Version sql.NullString `json:"version"` // version
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Metum] exists in the database.
func (m *Metum) Exists() bool {
	return m._exists
}

// Deleted returns true when the [Metum] has been marked for deletion
// from the database.
func (m *Metum) Deleted() bool {
	return m._deleted
}

// Insert inserts the [Metum] to the database.
func (m *Metum) Insert(ctx context.Context, db DB) error {
	switch {
	case m._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case m._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.meta (` +
		`date, version` +
		`) VALUES (` +
		`$1, $2` +
		`) RETURNING id`
	// run
	logf(sqlstr, m.Date, m.Version)
	if err := db.QueryRowContext(ctx, sqlstr, m.Date, m.Version).Scan(&m.ID); err != nil {
		return logerror(err)
	}
	// set exists
	m._exists = true
	return nil
}

// Update updates a [Metum] in the database.
func (m *Metum) Update(ctx context.Context, db DB) error {
	switch {
	case !m._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case m._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.meta SET ` +
		`date = $1, version = $2 ` +
		`WHERE id = $3`
	// run
	logf(sqlstr, m.Date, m.Version, m.ID)
	if _, err := db.ExecContext(ctx, sqlstr, m.Date, m.Version, m.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Metum] to the database.
func (m *Metum) Save(ctx context.Context, db DB) error {
	if m.Exists() {
		return m.Update(ctx, db)
	}
	return m.Insert(ctx, db)
}

// Upsert performs an upsert for [Metum].
func (m *Metum) Upsert(ctx context.Context, db DB) error {
	switch {
	case m._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.meta (` +
		`id, date, version` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`date = EXCLUDED.date, version = EXCLUDED.version `
	// run
	logf(sqlstr, m.ID, m.Date, m.Version)
	if _, err := db.ExecContext(ctx, sqlstr, m.ID, m.Date, m.Version); err != nil {
		return logerror(err)
	}
	// set exists
	m._exists = true
	return nil
}

// Delete deletes the [Metum] from the database.
func (m *Metum) Delete(ctx context.Context, db DB) error {
	switch {
	case !m._exists: // doesn't exist
		return nil
	case m._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.meta ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, m.ID)
	if _, err := db.ExecContext(ctx, sqlstr, m.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	m._deleted = true
	return nil
}

// MetumByID retrieves a row from 'public.meta' as a [Metum].
//
// Generated from index 'meta_pkey'.
func MetumByID(ctx context.Context, db DB, id int) (*Metum, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, date, version ` +
		`FROM public.meta ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	m := Metum{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&m.ID, &m.Date, &m.Version); err != nil {
		return nil, logerror(err)
	}
	return &m, nil
}
