package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Set represents a row from 'public.sets'.
type Set struct {
	ID               int            `json:"id"`               // id
	Basesetsize      sql.NullInt64  `json:"basesetsize"`      // basesetsize
	Block            sql.NullString `json:"block"`            // block
	Cardspheresetid  sql.NullInt64  `json:"cardspheresetid"`  // cardspheresetid
	Code             string         `json:"code"`             // code
	Isfoilonly       sql.NullBool   `json:"isfoilonly"`       // isfoilonly
	Isforeignonly    sql.NullBool   `json:"isforeignonly"`    // isforeignonly
	Isnonfoilonly    sql.NullBool   `json:"isnonfoilonly"`    // isnonfoilonly
	Isonlineonly     sql.NullBool   `json:"isonlineonly"`     // isonlineonly
	Ispartialpreview sql.NullBool   `json:"ispartialpreview"` // ispartialpreview
	Keyrunecode      sql.NullString `json:"keyrunecode"`      // keyrunecode
	Languages        sql.NullString `json:"languages"`        // languages
	Mcmid            sql.NullInt64  `json:"mcmid"`            // mcmid
	Mcmidextras      sql.NullInt64  `json:"mcmidextras"`      // mcmidextras
	Mcmname          sql.NullString `json:"mcmname"`          // mcmname
	Mtgocode         sql.NullString `json:"mtgocode"`         // mtgocode
	Name             sql.NullString `json:"name"`             // name
	Parentcode       sql.NullString `json:"parentcode"`       // parentcode
	Releasedate      sql.NullString `json:"releasedate"`      // releasedate
	Tcgplayergroupid sql.NullInt64  `json:"tcgplayergroupid"` // tcgplayergroupid
	Tokensetcode     sql.NullString `json:"tokensetcode"`     // tokensetcode
	Totalsetsize     sql.NullInt64  `json:"totalsetsize"`     // totalsetsize
	Type             sql.NullString `json:"type"`             // type
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Set] exists in the database.
func (s *Set) Exists() bool {
	return s._exists
}

// Deleted returns true when the [Set] has been marked for deletion
// from the database.
func (s *Set) Deleted() bool {
	return s._deleted
}

// Insert inserts the [Set] to the database.
func (s *Set) Insert(ctx context.Context, db DB) error {
	switch {
	case s._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case s._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.sets (` +
		`basesetsize, block, cardspheresetid, code, isfoilonly, isforeignonly, isnonfoilonly, isonlineonly, ispartialpreview, keyrunecode, languages, mcmid, mcmidextras, mcmname, mtgocode, name, parentcode, releasedate, tcgplayergroupid, tokensetcode, totalsetsize, type` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22` +
		`) RETURNING id`
	// run
	logf(sqlstr, s.Basesetsize, s.Block, s.Cardspheresetid, s.Code, s.Isfoilonly, s.Isforeignonly, s.Isnonfoilonly, s.Isonlineonly, s.Ispartialpreview, s.Keyrunecode, s.Languages, s.Mcmid, s.Mcmidextras, s.Mcmname, s.Mtgocode, s.Name, s.Parentcode, s.Releasedate, s.Tcgplayergroupid, s.Tokensetcode, s.Totalsetsize, s.Type)
	if err := db.QueryRowContext(ctx, sqlstr, s.Basesetsize, s.Block, s.Cardspheresetid, s.Code, s.Isfoilonly, s.Isforeignonly, s.Isnonfoilonly, s.Isonlineonly, s.Ispartialpreview, s.Keyrunecode, s.Languages, s.Mcmid, s.Mcmidextras, s.Mcmname, s.Mtgocode, s.Name, s.Parentcode, s.Releasedate, s.Tcgplayergroupid, s.Tokensetcode, s.Totalsetsize, s.Type).Scan(&s.ID); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Update updates a [Set] in the database.
func (s *Set) Update(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case s._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.sets SET ` +
		`basesetsize = $1, block = $2, cardspheresetid = $3, code = $4, isfoilonly = $5, isforeignonly = $6, isnonfoilonly = $7, isonlineonly = $8, ispartialpreview = $9, keyrunecode = $10, languages = $11, mcmid = $12, mcmidextras = $13, mcmname = $14, mtgocode = $15, name = $16, parentcode = $17, releasedate = $18, tcgplayergroupid = $19, tokensetcode = $20, totalsetsize = $21, type = $22 ` +
		`WHERE id = $23`
	// run
	logf(sqlstr, s.Basesetsize, s.Block, s.Cardspheresetid, s.Code, s.Isfoilonly, s.Isforeignonly, s.Isnonfoilonly, s.Isonlineonly, s.Ispartialpreview, s.Keyrunecode, s.Languages, s.Mcmid, s.Mcmidextras, s.Mcmname, s.Mtgocode, s.Name, s.Parentcode, s.Releasedate, s.Tcgplayergroupid, s.Tokensetcode, s.Totalsetsize, s.Type, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.Basesetsize, s.Block, s.Cardspheresetid, s.Code, s.Isfoilonly, s.Isforeignonly, s.Isnonfoilonly, s.Isonlineonly, s.Ispartialpreview, s.Keyrunecode, s.Languages, s.Mcmid, s.Mcmidextras, s.Mcmname, s.Mtgocode, s.Name, s.Parentcode, s.Releasedate, s.Tcgplayergroupid, s.Tokensetcode, s.Totalsetsize, s.Type, s.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Set] to the database.
func (s *Set) Save(ctx context.Context, db DB) error {
	if s.Exists() {
		return s.Update(ctx, db)
	}
	return s.Insert(ctx, db)
}

// Upsert performs an upsert for [Set].
func (s *Set) Upsert(ctx context.Context, db DB) error {
	switch {
	case s._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.sets (` +
		`id, basesetsize, block, cardspheresetid, code, isfoilonly, isforeignonly, isnonfoilonly, isonlineonly, ispartialpreview, keyrunecode, languages, mcmid, mcmidextras, mcmname, mtgocode, name, parentcode, releasedate, tcgplayergroupid, tokensetcode, totalsetsize, type` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`basesetsize = EXCLUDED.basesetsize, block = EXCLUDED.block, cardspheresetid = EXCLUDED.cardspheresetid, code = EXCLUDED.code, isfoilonly = EXCLUDED.isfoilonly, isforeignonly = EXCLUDED.isforeignonly, isnonfoilonly = EXCLUDED.isnonfoilonly, isonlineonly = EXCLUDED.isonlineonly, ispartialpreview = EXCLUDED.ispartialpreview, keyrunecode = EXCLUDED.keyrunecode, languages = EXCLUDED.languages, mcmid = EXCLUDED.mcmid, mcmidextras = EXCLUDED.mcmidextras, mcmname = EXCLUDED.mcmname, mtgocode = EXCLUDED.mtgocode, name = EXCLUDED.name, parentcode = EXCLUDED.parentcode, releasedate = EXCLUDED.releasedate, tcgplayergroupid = EXCLUDED.tcgplayergroupid, tokensetcode = EXCLUDED.tokensetcode, totalsetsize = EXCLUDED.totalsetsize, type = EXCLUDED.type `
	// run
	logf(sqlstr, s.ID, s.Basesetsize, s.Block, s.Cardspheresetid, s.Code, s.Isfoilonly, s.Isforeignonly, s.Isnonfoilonly, s.Isonlineonly, s.Ispartialpreview, s.Keyrunecode, s.Languages, s.Mcmid, s.Mcmidextras, s.Mcmname, s.Mtgocode, s.Name, s.Parentcode, s.Releasedate, s.Tcgplayergroupid, s.Tokensetcode, s.Totalsetsize, s.Type)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID, s.Basesetsize, s.Block, s.Cardspheresetid, s.Code, s.Isfoilonly, s.Isforeignonly, s.Isnonfoilonly, s.Isonlineonly, s.Ispartialpreview, s.Keyrunecode, s.Languages, s.Mcmid, s.Mcmidextras, s.Mcmname, s.Mtgocode, s.Name, s.Parentcode, s.Releasedate, s.Tcgplayergroupid, s.Tokensetcode, s.Totalsetsize, s.Type); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Delete deletes the [Set] from the database.
func (s *Set) Delete(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return nil
	case s._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.sets ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	s._deleted = true
	return nil
}

// SetByCode retrieves a row from 'public.sets' as a [Set].
//
// Generated from index 'sets_code_key'.
func SetByCode(ctx context.Context, db DB, code string) (*Set, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, basesetsize, block, cardspheresetid, code, isfoilonly, isforeignonly, isnonfoilonly, isonlineonly, ispartialpreview, keyrunecode, languages, mcmid, mcmidextras, mcmname, mtgocode, name, parentcode, releasedate, tcgplayergroupid, tokensetcode, totalsetsize, type ` +
		`FROM public.sets ` +
		`WHERE code = $1`
	// run
	logf(sqlstr, code)
	s := Set{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, code).Scan(&s.ID, &s.Basesetsize, &s.Block, &s.Cardspheresetid, &s.Code, &s.Isfoilonly, &s.Isforeignonly, &s.Isnonfoilonly, &s.Isonlineonly, &s.Ispartialpreview, &s.Keyrunecode, &s.Languages, &s.Mcmid, &s.Mcmidextras, &s.Mcmname, &s.Mtgocode, &s.Name, &s.Parentcode, &s.Releasedate, &s.Tcgplayergroupid, &s.Tokensetcode, &s.Totalsetsize, &s.Type); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}

// SetByID retrieves a row from 'public.sets' as a [Set].
//
// Generated from index 'sets_pkey'.
func SetByID(ctx context.Context, db DB, id int) (*Set, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, basesetsize, block, cardspheresetid, code, isfoilonly, isforeignonly, isnonfoilonly, isonlineonly, ispartialpreview, keyrunecode, languages, mcmid, mcmidextras, mcmname, mtgocode, name, parentcode, releasedate, tcgplayergroupid, tokensetcode, totalsetsize, type ` +
		`FROM public.sets ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	s := Set{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&s.ID, &s.Basesetsize, &s.Block, &s.Cardspheresetid, &s.Code, &s.Isfoilonly, &s.Isforeignonly, &s.Isnonfoilonly, &s.Isonlineonly, &s.Ispartialpreview, &s.Keyrunecode, &s.Languages, &s.Mcmid, &s.Mcmidextras, &s.Mcmname, &s.Mtgocode, &s.Name, &s.Parentcode, &s.Releasedate, &s.Tcgplayergroupid, &s.Tokensetcode, &s.Totalsetsize, &s.Type); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}
