package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Setboostercontentweight represents a row from 'public.setboostercontentweights'.
type Setboostercontentweight struct {
	ID            int            `json:"id"`            // id
	Boosterindex  sql.NullInt64  `json:"boosterindex"`  // boosterindex
	Boostername   sql.NullString `json:"boostername"`   // boostername
	Boosterweight sql.NullInt64  `json:"boosterweight"` // boosterweight
	Setcode       sql.NullString `json:"setcode"`       // setcode
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Setboostercontentweight] exists in the database.
func (s *Setboostercontentweight) Exists() bool {
	return s._exists
}

// Deleted returns true when the [Setboostercontentweight] has been marked for deletion
// from the database.
func (s *Setboostercontentweight) Deleted() bool {
	return s._deleted
}

// Insert inserts the [Setboostercontentweight] to the database.
func (s *Setboostercontentweight) Insert(ctx context.Context, db DB) error {
	switch {
	case s._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case s._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.setboostercontentweights (` +
		`boosterindex, boostername, boosterweight, setcode` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) RETURNING id`
	// run
	logf(sqlstr, s.Boosterindex, s.Boostername, s.Boosterweight, s.Setcode)
	if err := db.QueryRowContext(ctx, sqlstr, s.Boosterindex, s.Boostername, s.Boosterweight, s.Setcode).Scan(&s.ID); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Update updates a [Setboostercontentweight] in the database.
func (s *Setboostercontentweight) Update(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case s._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.setboostercontentweights SET ` +
		`boosterindex = $1, boostername = $2, boosterweight = $3, setcode = $4 ` +
		`WHERE id = $5`
	// run
	logf(sqlstr, s.Boosterindex, s.Boostername, s.Boosterweight, s.Setcode, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.Boosterindex, s.Boostername, s.Boosterweight, s.Setcode, s.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Setboostercontentweight] to the database.
func (s *Setboostercontentweight) Save(ctx context.Context, db DB) error {
	if s.Exists() {
		return s.Update(ctx, db)
	}
	return s.Insert(ctx, db)
}

// Upsert performs an upsert for [Setboostercontentweight].
func (s *Setboostercontentweight) Upsert(ctx context.Context, db DB) error {
	switch {
	case s._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.setboostercontentweights (` +
		`id, boosterindex, boostername, boosterweight, setcode` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`boosterindex = EXCLUDED.boosterindex, boostername = EXCLUDED.boostername, boosterweight = EXCLUDED.boosterweight, setcode = EXCLUDED.setcode `
	// run
	logf(sqlstr, s.ID, s.Boosterindex, s.Boostername, s.Boosterweight, s.Setcode)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID, s.Boosterindex, s.Boostername, s.Boosterweight, s.Setcode); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Delete deletes the [Setboostercontentweight] from the database.
func (s *Setboostercontentweight) Delete(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return nil
	case s._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.setboostercontentweights ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	s._deleted = true
	return nil
}

// SetboostercontentweightByID retrieves a row from 'public.setboostercontentweights' as a [Setboostercontentweight].
//
// Generated from index 'setboostercontentweights_pkey'.
func SetboostercontentweightByID(ctx context.Context, db DB, id int) (*Setboostercontentweight, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boosterindex, boostername, boosterweight, setcode ` +
		`FROM public.setboostercontentweights ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	s := Setboostercontentweight{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&s.ID, &s.Boosterindex, &s.Boostername, &s.Boosterweight, &s.Setcode); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}
