package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Setboostersheetcard represents a row from 'public.setboostersheetcards'.
type Setboostersheetcard struct {
	ID          int            `json:"id"`          // id
	Boostername sql.NullString `json:"boostername"` // boostername
	Carduuid    string         `json:"carduuid"`    // carduuid
	Cardweight  sql.NullInt64  `json:"cardweight"`  // cardweight
	Setcode     sql.NullString `json:"setcode"`     // setcode
	Sheetname   sql.NullString `json:"sheetname"`   // sheetname
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Setboostersheetcard] exists in the database.
func (s *Setboostersheetcard) Exists() bool {
	return s._exists
}

// Deleted returns true when the [Setboostersheetcard] has been marked for deletion
// from the database.
func (s *Setboostersheetcard) Deleted() bool {
	return s._deleted
}

// Insert inserts the [Setboostersheetcard] to the database.
func (s *Setboostersheetcard) Insert(ctx context.Context, db DB) error {
	switch {
	case s._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case s._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.setboostersheetcards (` +
		`boostername, carduuid, cardweight, setcode, sheetname` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) RETURNING id`
	// run
	logf(sqlstr, s.Boostername, s.Carduuid, s.Cardweight, s.Setcode, s.Sheetname)
	if err := db.QueryRowContext(ctx, sqlstr, s.Boostername, s.Carduuid, s.Cardweight, s.Setcode, s.Sheetname).Scan(&s.ID); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Update updates a [Setboostersheetcard] in the database.
func (s *Setboostersheetcard) Update(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case s._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.setboostersheetcards SET ` +
		`boostername = $1, carduuid = $2, cardweight = $3, setcode = $4, sheetname = $5 ` +
		`WHERE id = $6`
	// run
	logf(sqlstr, s.Boostername, s.Carduuid, s.Cardweight, s.Setcode, s.Sheetname, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.Boostername, s.Carduuid, s.Cardweight, s.Setcode, s.Sheetname, s.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Setboostersheetcard] to the database.
func (s *Setboostersheetcard) Save(ctx context.Context, db DB) error {
	if s.Exists() {
		return s.Update(ctx, db)
	}
	return s.Insert(ctx, db)
}

// Upsert performs an upsert for [Setboostersheetcard].
func (s *Setboostersheetcard) Upsert(ctx context.Context, db DB) error {
	switch {
	case s._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.setboostersheetcards (` +
		`id, boostername, carduuid, cardweight, setcode, sheetname` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`boostername = EXCLUDED.boostername, carduuid = EXCLUDED.carduuid, cardweight = EXCLUDED.cardweight, setcode = EXCLUDED.setcode, sheetname = EXCLUDED.sheetname `
	// run
	logf(sqlstr, s.ID, s.Boostername, s.Carduuid, s.Cardweight, s.Setcode, s.Sheetname)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID, s.Boostername, s.Carduuid, s.Cardweight, s.Setcode, s.Sheetname); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Delete deletes the [Setboostersheetcard] from the database.
func (s *Setboostersheetcard) Delete(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return nil
	case s._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.setboostersheetcards ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	s._deleted = true
	return nil
}

// SetboostersheetcardByID retrieves a row from 'public.setboostersheetcards' as a [Setboostersheetcard].
//
// Generated from index 'setboostersheetcards_pkey'.
func SetboostersheetcardByID(ctx context.Context, db DB, id int) (*Setboostersheetcard, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boostername, carduuid, cardweight, setcode, sheetname ` +
		`FROM public.setboostersheetcards ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	s := Setboostersheetcard{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&s.ID, &s.Boostername, &s.Carduuid, &s.Cardweight, &s.Setcode, &s.Sheetname); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}

// SetboostersheetcardBySetcodeSheetnameBoosternameCarduuid retrieves a row from 'public.setboostersheetcards' as a [Setboostersheetcard].
//
// Generated from index 'setboostersheetcards_setcode_sheetname_boostername_carduuid_key'.
func SetboostersheetcardBySetcodeSheetnameBoosternameCarduuid(ctx context.Context, db DB, setcode, sheetname, boostername sql.NullString, carduuid string) (*Setboostersheetcard, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boostername, carduuid, cardweight, setcode, sheetname ` +
		`FROM public.setboostersheetcards ` +
		`WHERE setcode = $1 AND sheetname = $2 AND boostername = $3 AND carduuid = $4`
	// run
	logf(sqlstr, setcode, sheetname, boostername, carduuid)
	s := Setboostersheetcard{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, setcode, sheetname, boostername, carduuid).Scan(&s.ID, &s.Boostername, &s.Carduuid, &s.Cardweight, &s.Setcode, &s.Sheetname); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}
