package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Setboostersheet represents a row from 'public.setboostersheets'.
type Setboostersheet struct {
	ID                    int            `json:"id"`                    // id
	Boostername           sql.NullString `json:"boostername"`           // boostername
	Setcode               sql.NullString `json:"setcode"`               // setcode
	Sheethasbalancecolors sql.NullBool   `json:"sheethasbalancecolors"` // sheethasbalancecolors
	Sheetisfoil           sql.NullBool   `json:"sheetisfoil"`           // sheetisfoil
	Sheetname             sql.NullString `json:"sheetname"`             // sheetname
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Setboostersheet] exists in the database.
func (s *Setboostersheet) Exists() bool {
	return s._exists
}

// Deleted returns true when the [Setboostersheet] has been marked for deletion
// from the database.
func (s *Setboostersheet) Deleted() bool {
	return s._deleted
}

// Insert inserts the [Setboostersheet] to the database.
func (s *Setboostersheet) Insert(ctx context.Context, db DB) error {
	switch {
	case s._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case s._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.setboostersheets (` +
		`boostername, setcode, sheethasbalancecolors, sheetisfoil, sheetname` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) RETURNING id`
	// run
	logf(sqlstr, s.Boostername, s.Setcode, s.Sheethasbalancecolors, s.Sheetisfoil, s.Sheetname)
	if err := db.QueryRowContext(ctx, sqlstr, s.Boostername, s.Setcode, s.Sheethasbalancecolors, s.Sheetisfoil, s.Sheetname).Scan(&s.ID); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Update updates a [Setboostersheet] in the database.
func (s *Setboostersheet) Update(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case s._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.setboostersheets SET ` +
		`boostername = $1, setcode = $2, sheethasbalancecolors = $3, sheetisfoil = $4, sheetname = $5 ` +
		`WHERE id = $6`
	// run
	logf(sqlstr, s.Boostername, s.Setcode, s.Sheethasbalancecolors, s.Sheetisfoil, s.Sheetname, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.Boostername, s.Setcode, s.Sheethasbalancecolors, s.Sheetisfoil, s.Sheetname, s.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Setboostersheet] to the database.
func (s *Setboostersheet) Save(ctx context.Context, db DB) error {
	if s.Exists() {
		return s.Update(ctx, db)
	}
	return s.Insert(ctx, db)
}

// Upsert performs an upsert for [Setboostersheet].
func (s *Setboostersheet) Upsert(ctx context.Context, db DB) error {
	switch {
	case s._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.setboostersheets (` +
		`id, boostername, setcode, sheethasbalancecolors, sheetisfoil, sheetname` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`boostername = EXCLUDED.boostername, setcode = EXCLUDED.setcode, sheethasbalancecolors = EXCLUDED.sheethasbalancecolors, sheetisfoil = EXCLUDED.sheetisfoil, sheetname = EXCLUDED.sheetname `
	// run
	logf(sqlstr, s.ID, s.Boostername, s.Setcode, s.Sheethasbalancecolors, s.Sheetisfoil, s.Sheetname)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID, s.Boostername, s.Setcode, s.Sheethasbalancecolors, s.Sheetisfoil, s.Sheetname); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Delete deletes the [Setboostersheet] from the database.
func (s *Setboostersheet) Delete(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return nil
	case s._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.setboostersheets ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	s._deleted = true
	return nil
}

// SetboostersheetByID retrieves a row from 'public.setboostersheets' as a [Setboostersheet].
//
// Generated from index 'setboostersheets_pkey'.
func SetboostersheetByID(ctx context.Context, db DB, id int) (*Setboostersheet, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boostername, setcode, sheethasbalancecolors, sheetisfoil, sheetname ` +
		`FROM public.setboostersheets ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	s := Setboostersheet{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&s.ID, &s.Boostername, &s.Setcode, &s.Sheethasbalancecolors, &s.Sheetisfoil, &s.Sheetname); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}

// SetboostersheetBySetcodeSheetnameBoostername retrieves a row from 'public.setboostersheets' as a [Setboostersheet].
//
// Generated from index 'setboostersheets_setcode_sheetname_boostername_key'.
func SetboostersheetBySetcodeSheetnameBoostername(ctx context.Context, db DB, setcode, sheetname, boostername sql.NullString) (*Setboostersheet, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boostername, setcode, sheethasbalancecolors, sheetisfoil, sheetname ` +
		`FROM public.setboostersheets ` +
		`WHERE setcode = $1 AND sheetname = $2 AND boostername = $3`
	// run
	logf(sqlstr, setcode, sheetname, boostername)
	s := Setboostersheet{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, setcode, sheetname, boostername).Scan(&s.ID, &s.Boostername, &s.Setcode, &s.Sheethasbalancecolors, &s.Sheetisfoil, &s.Sheetname); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}
