package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Setboostercontent represents a row from 'public.setboostercontents'.
type Setboostercontent struct {
	ID           int            `json:"id"`           // id
	Boosterindex sql.NullInt64  `json:"boosterindex"` // boosterindex
	Boostername  sql.NullString `json:"boostername"`  // boostername
	Setcode      sql.NullString `json:"setcode"`      // setcode
	Sheetname    sql.NullString `json:"sheetname"`    // sheetname
	Sheetpicks   sql.NullInt64  `json:"sheetpicks"`   // sheetpicks
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Setboostercontent] exists in the database.
func (s *Setboostercontent) Exists() bool {
	return s._exists
}

// Deleted returns true when the [Setboostercontent] has been marked for deletion
// from the database.
func (s *Setboostercontent) Deleted() bool {
	return s._deleted
}

// Insert inserts the [Setboostercontent] to the database.
func (s *Setboostercontent) Insert(ctx context.Context, db DB) error {
	switch {
	case s._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case s._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.setboostercontents (` +
		`boosterindex, boostername, setcode, sheetname, sheetpicks` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) RETURNING id`
	// run
	logf(sqlstr, s.Boosterindex, s.Boostername, s.Setcode, s.Sheetname, s.Sheetpicks)
	if err := db.QueryRowContext(ctx, sqlstr, s.Boosterindex, s.Boostername, s.Setcode, s.Sheetname, s.Sheetpicks).Scan(&s.ID); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Update updates a [Setboostercontent] in the database.
func (s *Setboostercontent) Update(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case s._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.setboostercontents SET ` +
		`boosterindex = $1, boostername = $2, setcode = $3, sheetname = $4, sheetpicks = $5 ` +
		`WHERE id = $6`
	// run
	logf(sqlstr, s.Boosterindex, s.Boostername, s.Setcode, s.Sheetname, s.Sheetpicks, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.Boosterindex, s.Boostername, s.Setcode, s.Sheetname, s.Sheetpicks, s.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Setboostercontent] to the database.
func (s *Setboostercontent) Save(ctx context.Context, db DB) error {
	if s.Exists() {
		return s.Update(ctx, db)
	}
	return s.Insert(ctx, db)
}

// Upsert performs an upsert for [Setboostercontent].
func (s *Setboostercontent) Upsert(ctx context.Context, db DB) error {
	switch {
	case s._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.setboostercontents (` +
		`id, boosterindex, boostername, setcode, sheetname, sheetpicks` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`boosterindex = EXCLUDED.boosterindex, boostername = EXCLUDED.boostername, setcode = EXCLUDED.setcode, sheetname = EXCLUDED.sheetname, sheetpicks = EXCLUDED.sheetpicks `
	// run
	logf(sqlstr, s.ID, s.Boosterindex, s.Boostername, s.Setcode, s.Sheetname, s.Sheetpicks)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID, s.Boosterindex, s.Boostername, s.Setcode, s.Sheetname, s.Sheetpicks); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Delete deletes the [Setboostercontent] from the database.
func (s *Setboostercontent) Delete(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return nil
	case s._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.setboostercontents ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	s._deleted = true
	return nil
}

// SetboostercontentByID retrieves a row from 'public.setboostercontents' as a [Setboostercontent].
//
// Generated from index 'setboostercontents_pkey'.
func SetboostercontentByID(ctx context.Context, db DB, id int) (*Setboostercontent, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boosterindex, boostername, setcode, sheetname, sheetpicks ` +
		`FROM public.setboostercontents ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	s := Setboostercontent{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&s.ID, &s.Boosterindex, &s.Boostername, &s.Setcode, &s.Sheetname, &s.Sheetpicks); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}

// SetboostercontentBySetcodeSheetnameBoosternameBoosterindex retrieves a row from 'public.setboostercontents' as a [Setboostercontent].
//
// Generated from index 'setboostercontents_setcode_sheetname_boostername_boosterind_key'.
func SetboostercontentBySetcodeSheetnameBoosternameBoosterindex(ctx context.Context, db DB, setcode, sheetname, boostername sql.NullString, boosterindex sql.NullInt64) (*Setboostercontent, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, boosterindex, boostername, setcode, sheetname, sheetpicks ` +
		`FROM public.setboostercontents ` +
		`WHERE setcode = $1 AND sheetname = $2 AND boostername = $3 AND boosterindex = $4`
	// run
	logf(sqlstr, setcode, sheetname, boostername, boosterindex)
	s := Setboostercontent{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, setcode, sheetname, boostername, boosterindex).Scan(&s.ID, &s.Boosterindex, &s.Boostername, &s.Setcode, &s.Sheetname, &s.Sheetpicks); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}
