package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Settranslation represents a row from 'public.settranslations'.
type Settranslation struct {
	ID          int            `json:"id"`          // id
	Language    sql.NullString `json:"language"`    // language
	Setcode     sql.NullString `json:"setcode"`     // setcode
	Translation sql.NullString `json:"translation"` // translation
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Settranslation] exists in the database.
func (s *Settranslation) Exists() bool {
	return s._exists
}

// Deleted returns true when the [Settranslation] has been marked for deletion
// from the database.
func (s *Settranslation) Deleted() bool {
	return s._deleted
}

// Insert inserts the [Settranslation] to the database.
func (s *Settranslation) Insert(ctx context.Context, db DB) error {
	switch {
	case s._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case s._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.settranslations (` +
		`language, setcode, translation` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) RETURNING id`
	// run
	logf(sqlstr, s.Language, s.Setcode, s.Translation)
	if err := db.QueryRowContext(ctx, sqlstr, s.Language, s.Setcode, s.Translation).Scan(&s.ID); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Update updates a [Settranslation] in the database.
func (s *Settranslation) Update(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case s._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.settranslations SET ` +
		`language = $1, setcode = $2, translation = $3 ` +
		`WHERE id = $4`
	// run
	logf(sqlstr, s.Language, s.Setcode, s.Translation, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.Language, s.Setcode, s.Translation, s.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Settranslation] to the database.
func (s *Settranslation) Save(ctx context.Context, db DB) error {
	if s.Exists() {
		return s.Update(ctx, db)
	}
	return s.Insert(ctx, db)
}

// Upsert performs an upsert for [Settranslation].
func (s *Settranslation) Upsert(ctx context.Context, db DB) error {
	switch {
	case s._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.settranslations (` +
		`id, language, setcode, translation` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`language = EXCLUDED.language, setcode = EXCLUDED.setcode, translation = EXCLUDED.translation `
	// run
	logf(sqlstr, s.ID, s.Language, s.Setcode, s.Translation)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID, s.Language, s.Setcode, s.Translation); err != nil {
		return logerror(err)
	}
	// set exists
	s._exists = true
	return nil
}

// Delete deletes the [Settranslation] from the database.
func (s *Settranslation) Delete(ctx context.Context, db DB) error {
	switch {
	case !s._exists: // doesn't exist
		return nil
	case s._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.settranslations ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, s.ID)
	if _, err := db.ExecContext(ctx, sqlstr, s.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	s._deleted = true
	return nil
}

// SettranslationByID retrieves a row from 'public.settranslations' as a [Settranslation].
//
// Generated from index 'settranslations_pkey'.
func SettranslationByID(ctx context.Context, db DB, id int) (*Settranslation, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, language, setcode, translation ` +
		`FROM public.settranslations ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	s := Settranslation{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&s.ID, &s.Language, &s.Setcode, &s.Translation); err != nil {
		return nil, logerror(err)
	}
	return &s, nil
}
