package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"github.com/google/uuid"
)

// StagingPrice represents a row from 'public.staging_prices'.
type StagingPrice struct {
	UUID      uuid.NullUUID `json:"uuid"`       // uuid
	TcgPrices []byte        `json:"tcg_prices"` // tcg_prices
}
