package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"

	"github.com/google/uuid"
)

// TodaysPrice represents a row from 'public.todays_prices'.
type TodaysPrice struct {
	ID        int           `json:"id"`         // id
	CardUUID  uuid.NullUUID `json:"card_uuid"`  // card_uuid
	PriceData []byte        `json:"price_data"` // price_data
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [TodaysPrice] exists in the database.
func (tp *TodaysPrice) Exists() bool {
	return tp._exists
}

// Deleted returns true when the [TodaysPrice] has been marked for deletion
// from the database.
func (tp *TodaysPrice) Deleted() bool {
	return tp._deleted
}

// Insert inserts the [TodaysPrice] to the database.
func (tp *TodaysPrice) Insert(ctx context.Context, db DB) error {
	switch {
	case tp._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case tp._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.todays_prices (` +
		`card_uuid, price_data` +
		`) VALUES (` +
		`$1, $2` +
		`) RETURNING id`
	// run
	logf(sqlstr, tp.CardUUID, tp.PriceData)
	if err := db.QueryRowContext(ctx, sqlstr, tp.CardUUID, tp.PriceData).Scan(&tp.ID); err != nil {
		return logerror(err)
	}
	// set exists
	tp._exists = true
	return nil
}

// Update updates a [TodaysPrice] in the database.
func (tp *TodaysPrice) Update(ctx context.Context, db DB) error {
	switch {
	case !tp._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case tp._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.todays_prices SET ` +
		`card_uuid = $1, price_data = $2 ` +
		`WHERE id = $3`
	// run
	logf(sqlstr, tp.CardUUID, tp.PriceData, tp.ID)
	if _, err := db.ExecContext(ctx, sqlstr, tp.CardUUID, tp.PriceData, tp.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [TodaysPrice] to the database.
func (tp *TodaysPrice) Save(ctx context.Context, db DB) error {
	if tp.Exists() {
		return tp.Update(ctx, db)
	}
	return tp.Insert(ctx, db)
}

// Upsert performs an upsert for [TodaysPrice].
func (tp *TodaysPrice) Upsert(ctx context.Context, db DB) error {
	switch {
	case tp._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.todays_prices (` +
		`id, card_uuid, price_data` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`card_uuid = EXCLUDED.card_uuid, price_data = EXCLUDED.price_data `
	// run
	logf(sqlstr, tp.ID, tp.CardUUID, tp.PriceData)
	if _, err := db.ExecContext(ctx, sqlstr, tp.ID, tp.CardUUID, tp.PriceData); err != nil {
		return logerror(err)
	}
	// set exists
	tp._exists = true
	return nil
}

// Delete deletes the [TodaysPrice] from the database.
func (tp *TodaysPrice) Delete(ctx context.Context, db DB) error {
	switch {
	case !tp._exists: // doesn't exist
		return nil
	case tp._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.todays_prices ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, tp.ID)
	if _, err := db.ExecContext(ctx, sqlstr, tp.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	tp._deleted = true
	return nil
}

// TodaysPriceByID retrieves a row from 'public.todays_prices' as a [TodaysPrice].
//
// Generated from index 'todays_prices_pkey'.
func TodaysPriceByID(ctx context.Context, db DB, id int) (*TodaysPrice, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, card_uuid, price_data ` +
		`FROM public.todays_prices ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	tp := TodaysPrice{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&tp.ID, &tp.CardUUID, &tp.PriceData); err != nil {
		return nil, logerror(err)
	}
	return &tp, nil
}
