package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Tokenidentifier represents a row from 'public.tokenidentifiers'.
type Tokenidentifier struct {
	ID                       int            `json:"id"`                       // id
	Cardkingdometchedid      sql.NullString `json:"cardkingdometchedid"`      // cardkingdometchedid
	Cardkingdomfoilid        sql.NullString `json:"cardkingdomfoilid"`        // cardkingdomfoilid
	Cardkingdomid            sql.NullString `json:"cardkingdomid"`            // cardkingdomid
	Cardspherefoilid         sql.NullString `json:"cardspherefoilid"`         // cardspherefoilid
	Cardsphereid             sql.NullString `json:"cardsphereid"`             // cardsphereid
	Deckboxid                sql.NullString `json:"deckboxid"`                // deckboxid
	Mcmid                    sql.NullString `json:"mcmid"`                    // mcmid
	Mcmmetaid                sql.NullString `json:"mcmmetaid"`                // mcmmetaid
	Mtgarenaid               sql.NullString `json:"mtgarenaid"`               // mtgarenaid
	Mtgjsonfoilversionid     sql.NullString `json:"mtgjsonfoilversionid"`     // mtgjsonfoilversionid
	Mtgjsonnonfoilversionid  sql.NullString `json:"mtgjsonnonfoilversionid"`  // mtgjsonnonfoilversionid
	Mtgjsonv4id              sql.NullString `json:"mtgjsonv4id"`              // mtgjsonv4id
	Mtgofoilid               sql.NullString `json:"mtgofoilid"`               // mtgofoilid
	Mtgoid                   sql.NullString `json:"mtgoid"`                   // mtgoid
	Multiverseid             sql.NullString `json:"multiverseid"`             // multiverseid
	Scryfallcardbackid       sql.NullString `json:"scryfallcardbackid"`       // scryfallcardbackid
	Scryfallid               sql.NullString `json:"scryfallid"`               // scryfallid
	Scryfallillustrationid   sql.NullString `json:"scryfallillustrationid"`   // scryfallillustrationid
	Scryfalloracleid         sql.NullString `json:"scryfalloracleid"`         // scryfalloracleid
	Tcgplayeretchedproductid sql.NullString `json:"tcgplayeretchedproductid"` // tcgplayeretchedproductid
	Tcgplayerproductid       sql.NullString `json:"tcgplayerproductid"`       // tcgplayerproductid
	UUID                     sql.NullString `json:"uuid"`                     // uuid
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Tokenidentifier] exists in the database.
func (t *Tokenidentifier) Exists() bool {
	return t._exists
}

// Deleted returns true when the [Tokenidentifier] has been marked for deletion
// from the database.
func (t *Tokenidentifier) Deleted() bool {
	return t._deleted
}

// Insert inserts the [Tokenidentifier] to the database.
func (t *Tokenidentifier) Insert(ctx context.Context, db DB) error {
	switch {
	case t._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case t._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.tokenidentifiers (` +
		`cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22` +
		`) RETURNING id`
	// run
	logf(sqlstr, t.Cardkingdometchedid, t.Cardkingdomfoilid, t.Cardkingdomid, t.Cardspherefoilid, t.Cardsphereid, t.Deckboxid, t.Mcmid, t.Mcmmetaid, t.Mtgarenaid, t.Mtgjsonfoilversionid, t.Mtgjsonnonfoilversionid, t.Mtgjsonv4id, t.Mtgofoilid, t.Mtgoid, t.Multiverseid, t.Scryfallcardbackid, t.Scryfallid, t.Scryfallillustrationid, t.Scryfalloracleid, t.Tcgplayeretchedproductid, t.Tcgplayerproductid, t.UUID)
	if err := db.QueryRowContext(ctx, sqlstr, t.Cardkingdometchedid, t.Cardkingdomfoilid, t.Cardkingdomid, t.Cardspherefoilid, t.Cardsphereid, t.Deckboxid, t.Mcmid, t.Mcmmetaid, t.Mtgarenaid, t.Mtgjsonfoilversionid, t.Mtgjsonnonfoilversionid, t.Mtgjsonv4id, t.Mtgofoilid, t.Mtgoid, t.Multiverseid, t.Scryfallcardbackid, t.Scryfallid, t.Scryfallillustrationid, t.Scryfalloracleid, t.Tcgplayeretchedproductid, t.Tcgplayerproductid, t.UUID).Scan(&t.ID); err != nil {
		return logerror(err)
	}
	// set exists
	t._exists = true
	return nil
}

// Update updates a [Tokenidentifier] in the database.
func (t *Tokenidentifier) Update(ctx context.Context, db DB) error {
	switch {
	case !t._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case t._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.tokenidentifiers SET ` +
		`cardkingdometchedid = $1, cardkingdomfoilid = $2, cardkingdomid = $3, cardspherefoilid = $4, cardsphereid = $5, deckboxid = $6, mcmid = $7, mcmmetaid = $8, mtgarenaid = $9, mtgjsonfoilversionid = $10, mtgjsonnonfoilversionid = $11, mtgjsonv4id = $12, mtgofoilid = $13, mtgoid = $14, multiverseid = $15, scryfallcardbackid = $16, scryfallid = $17, scryfallillustrationid = $18, scryfalloracleid = $19, tcgplayeretchedproductid = $20, tcgplayerproductid = $21, uuid = $22 ` +
		`WHERE id = $23`
	// run
	logf(sqlstr, t.Cardkingdometchedid, t.Cardkingdomfoilid, t.Cardkingdomid, t.Cardspherefoilid, t.Cardsphereid, t.Deckboxid, t.Mcmid, t.Mcmmetaid, t.Mtgarenaid, t.Mtgjsonfoilversionid, t.Mtgjsonnonfoilversionid, t.Mtgjsonv4id, t.Mtgofoilid, t.Mtgoid, t.Multiverseid, t.Scryfallcardbackid, t.Scryfallid, t.Scryfallillustrationid, t.Scryfalloracleid, t.Tcgplayeretchedproductid, t.Tcgplayerproductid, t.UUID, t.ID)
	if _, err := db.ExecContext(ctx, sqlstr, t.Cardkingdometchedid, t.Cardkingdomfoilid, t.Cardkingdomid, t.Cardspherefoilid, t.Cardsphereid, t.Deckboxid, t.Mcmid, t.Mcmmetaid, t.Mtgarenaid, t.Mtgjsonfoilversionid, t.Mtgjsonnonfoilversionid, t.Mtgjsonv4id, t.Mtgofoilid, t.Mtgoid, t.Multiverseid, t.Scryfallcardbackid, t.Scryfallid, t.Scryfallillustrationid, t.Scryfalloracleid, t.Tcgplayeretchedproductid, t.Tcgplayerproductid, t.UUID, t.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Tokenidentifier] to the database.
func (t *Tokenidentifier) Save(ctx context.Context, db DB) error {
	if t.Exists() {
		return t.Update(ctx, db)
	}
	return t.Insert(ctx, db)
}

// Upsert performs an upsert for [Tokenidentifier].
func (t *Tokenidentifier) Upsert(ctx context.Context, db DB) error {
	switch {
	case t._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.tokenidentifiers (` +
		`id, cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`cardkingdometchedid = EXCLUDED.cardkingdometchedid, cardkingdomfoilid = EXCLUDED.cardkingdomfoilid, cardkingdomid = EXCLUDED.cardkingdomid, cardspherefoilid = EXCLUDED.cardspherefoilid, cardsphereid = EXCLUDED.cardsphereid, deckboxid = EXCLUDED.deckboxid, mcmid = EXCLUDED.mcmid, mcmmetaid = EXCLUDED.mcmmetaid, mtgarenaid = EXCLUDED.mtgarenaid, mtgjsonfoilversionid = EXCLUDED.mtgjsonfoilversionid, mtgjsonnonfoilversionid = EXCLUDED.mtgjsonnonfoilversionid, mtgjsonv4id = EXCLUDED.mtgjsonv4id, mtgofoilid = EXCLUDED.mtgofoilid, mtgoid = EXCLUDED.mtgoid, multiverseid = EXCLUDED.multiverseid, scryfallcardbackid = EXCLUDED.scryfallcardbackid, scryfallid = EXCLUDED.scryfallid, scryfallillustrationid = EXCLUDED.scryfallillustrationid, scryfalloracleid = EXCLUDED.scryfalloracleid, tcgplayeretchedproductid = EXCLUDED.tcgplayeretchedproductid, tcgplayerproductid = EXCLUDED.tcgplayerproductid, uuid = EXCLUDED.uuid `
	// run
	logf(sqlstr, t.ID, t.Cardkingdometchedid, t.Cardkingdomfoilid, t.Cardkingdomid, t.Cardspherefoilid, t.Cardsphereid, t.Deckboxid, t.Mcmid, t.Mcmmetaid, t.Mtgarenaid, t.Mtgjsonfoilversionid, t.Mtgjsonnonfoilversionid, t.Mtgjsonv4id, t.Mtgofoilid, t.Mtgoid, t.Multiverseid, t.Scryfallcardbackid, t.Scryfallid, t.Scryfallillustrationid, t.Scryfalloracleid, t.Tcgplayeretchedproductid, t.Tcgplayerproductid, t.UUID)
	if _, err := db.ExecContext(ctx, sqlstr, t.ID, t.Cardkingdometchedid, t.Cardkingdomfoilid, t.Cardkingdomid, t.Cardspherefoilid, t.Cardsphereid, t.Deckboxid, t.Mcmid, t.Mcmmetaid, t.Mtgarenaid, t.Mtgjsonfoilversionid, t.Mtgjsonnonfoilversionid, t.Mtgjsonv4id, t.Mtgofoilid, t.Mtgoid, t.Multiverseid, t.Scryfallcardbackid, t.Scryfallid, t.Scryfallillustrationid, t.Scryfalloracleid, t.Tcgplayeretchedproductid, t.Tcgplayerproductid, t.UUID); err != nil {
		return logerror(err)
	}
	// set exists
	t._exists = true
	return nil
}

// Delete deletes the [Tokenidentifier] from the database.
func (t *Tokenidentifier) Delete(ctx context.Context, db DB) error {
	switch {
	case !t._exists: // doesn't exist
		return nil
	case t._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.tokenidentifiers ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, t.ID)
	if _, err := db.ExecContext(ctx, sqlstr, t.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	t._deleted = true
	return nil
}

// TokenidentifierByID retrieves a row from 'public.tokenidentifiers' as a [Tokenidentifier].
//
// Generated from index 'tokenidentifiers_pkey'.
func TokenidentifierByID(ctx context.Context, db DB, id int) (*Tokenidentifier, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid ` +
		`FROM public.tokenidentifiers ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	t := Tokenidentifier{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&t.ID, &t.Cardkingdometchedid, &t.Cardkingdomfoilid, &t.Cardkingdomid, &t.Cardspherefoilid, &t.Cardsphereid, &t.Deckboxid, &t.Mcmid, &t.Mcmmetaid, &t.Mtgarenaid, &t.Mtgjsonfoilversionid, &t.Mtgjsonnonfoilversionid, &t.Mtgjsonv4id, &t.Mtgofoilid, &t.Mtgoid, &t.Multiverseid, &t.Scryfallcardbackid, &t.Scryfallid, &t.Scryfallillustrationid, &t.Scryfalloracleid, &t.Tcgplayeretchedproductid, &t.Tcgplayerproductid, &t.UUID); err != nil {
		return nil, logerror(err)
	}
	return &t, nil
}

// TokenidentifiersByUUID retrieves a row from 'public.tokenidentifiers' as a [Tokenidentifier].
//
// Generated from index 'tokenidentifiers_uuid'.
func TokenidentifiersByUUID(ctx context.Context, db DB, uuid sql.NullString) ([]*Tokenidentifier, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, cardkingdometchedid, cardkingdomfoilid, cardkingdomid, cardspherefoilid, cardsphereid, deckboxid, mcmid, mcmmetaid, mtgarenaid, mtgjsonfoilversionid, mtgjsonnonfoilversionid, mtgjsonv4id, mtgofoilid, mtgoid, multiverseid, scryfallcardbackid, scryfallid, scryfallillustrationid, scryfalloracleid, tcgplayeretchedproductid, tcgplayerproductid, uuid ` +
		`FROM public.tokenidentifiers ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Tokenidentifier
	for rows.Next() {
		t := Tokenidentifier{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&t.ID, &t.Cardkingdometchedid, &t.Cardkingdomfoilid, &t.Cardkingdomid, &t.Cardspherefoilid, &t.Cardsphereid, &t.Deckboxid, &t.Mcmid, &t.Mcmmetaid, &t.Mtgarenaid, &t.Mtgjsonfoilversionid, &t.Mtgjsonnonfoilversionid, &t.Mtgjsonv4id, &t.Mtgofoilid, &t.Mtgoid, &t.Multiverseid, &t.Scryfallcardbackid, &t.Scryfallid, &t.Scryfallillustrationid, &t.Scryfalloracleid, &t.Tcgplayeretchedproductid, &t.Tcgplayerproductid, &t.UUID); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &t)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
