package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// Token represents a row from 'public.tokens'.
type Token struct {
	ID              int             `json:"id"`              // id
	Artist          sql.NullString  `json:"artist"`          // artist
	Artistids       sql.NullString  `json:"artistids"`       // artistids
	Asciiname       sql.NullString  `json:"asciiname"`       // asciiname
	Availability    sql.NullString  `json:"availability"`    // availability
	Boostertypes    sql.NullString  `json:"boostertypes"`    // boostertypes
	Bordercolor     sql.NullString  `json:"bordercolor"`     // bordercolor
	Coloridentity   sql.NullString  `json:"coloridentity"`   // coloridentity
	Colors          sql.NullString  `json:"colors"`          // colors
	Edhrecsaltiness sql.NullFloat64 `json:"edhrecsaltiness"` // edhrecsaltiness
	Facename        sql.NullString  `json:"facename"`        // facename
	Finishes        sql.NullString  `json:"finishes"`        // finishes
	Flavorname      sql.NullString  `json:"flavorname"`      // flavorname
	Flavortext      sql.NullString  `json:"flavortext"`      // flavortext
	Frameeffects    sql.NullString  `json:"frameeffects"`    // frameeffects
	Frameversion    sql.NullString  `json:"frameversion"`    // frameversion
	Hasfoil         sql.NullBool    `json:"hasfoil"`         // hasfoil
	Hasnonfoil      sql.NullBool    `json:"hasnonfoil"`      // hasnonfoil
	Isfullart       sql.NullBool    `json:"isfullart"`       // isfullart
	Isfunny         sql.NullBool    `json:"isfunny"`         // isfunny
	Isoversized     sql.NullBool    `json:"isoversized"`     // isoversized
	Ispromo         sql.NullBool    `json:"ispromo"`         // ispromo
	Isreprint       sql.NullBool    `json:"isreprint"`       // isreprint
	Istextless      sql.NullBool    `json:"istextless"`      // istextless
	Keywords        sql.NullString  `json:"keywords"`        // keywords
	Language        sql.NullString  `json:"language"`        // language
	Layout          sql.NullString  `json:"layout"`          // layout
	Manacost        sql.NullString  `json:"manacost"`        // manacost
	Name            sql.NullString  `json:"name"`            // name
	Number          sql.NullString  `json:"number"`          // number
	Orientation     sql.NullString  `json:"orientation"`     // orientation
	Originaltext    sql.NullString  `json:"originaltext"`    // originaltext
	Otherfaceids    sql.NullString  `json:"otherfaceids"`    // otherfaceids
	Power           sql.NullString  `json:"power"`           // power
	Promotypes      sql.NullString  `json:"promotypes"`      // promotypes
	Relatedcards    sql.NullString  `json:"relatedcards"`    // relatedcards
	Reverserelated  sql.NullString  `json:"reverserelated"`  // reverserelated
	Securitystamp   sql.NullString  `json:"securitystamp"`   // securitystamp
	Setcode         sql.NullString  `json:"setcode"`         // setcode
	Side            sql.NullString  `json:"side"`            // side
	Signature       sql.NullString  `json:"signature"`       // signature
	Subtypes        sql.NullString  `json:"subtypes"`        // subtypes
	Supertypes      sql.NullString  `json:"supertypes"`      // supertypes
	Text            sql.NullString  `json:"text"`            // text
	Toughness       sql.NullString  `json:"toughness"`       // toughness
	Type            sql.NullString  `json:"type"`            // type
	Types           sql.NullString  `json:"types"`           // types
	UUID            string          `json:"uuid"`            // uuid
	Watermark       sql.NullString  `json:"watermark"`       // watermark
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Token] exists in the database.
func (t *Token) Exists() bool {
	return t._exists
}

// Deleted returns true when the [Token] has been marked for deletion
// from the database.
func (t *Token) Deleted() bool {
	return t._deleted
}

// Insert inserts the [Token] to the database.
func (t *Token) Insert(ctx context.Context, db DB) error {
	switch {
	case t._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case t._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.tokens (` +
		`artist, artistids, asciiname, availability, boostertypes, bordercolor, coloridentity, colors, edhrecsaltiness, facename, finishes, flavorname, flavortext, frameeffects, frameversion, hasfoil, hasnonfoil, isfullart, isfunny, isoversized, ispromo, isreprint, istextless, keywords, language, layout, manacost, name, number, orientation, originaltext, otherfaceids, power, promotypes, relatedcards, reverserelated, securitystamp, setcode, side, signature, subtypes, supertypes, text, toughness, type, types, uuid, watermark` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48` +
		`) RETURNING id`
	// run
	logf(sqlstr, t.Artist, t.Artistids, t.Asciiname, t.Availability, t.Boostertypes, t.Bordercolor, t.Coloridentity, t.Colors, t.Edhrecsaltiness, t.Facename, t.Finishes, t.Flavorname, t.Flavortext, t.Frameeffects, t.Frameversion, t.Hasfoil, t.Hasnonfoil, t.Isfullart, t.Isfunny, t.Isoversized, t.Ispromo, t.Isreprint, t.Istextless, t.Keywords, t.Language, t.Layout, t.Manacost, t.Name, t.Number, t.Orientation, t.Originaltext, t.Otherfaceids, t.Power, t.Promotypes, t.Relatedcards, t.Reverserelated, t.Securitystamp, t.Setcode, t.Side, t.Signature, t.Subtypes, t.Supertypes, t.Text, t.Toughness, t.Type, t.Types, t.UUID, t.Watermark)
	if err := db.QueryRowContext(ctx, sqlstr, t.Artist, t.Artistids, t.Asciiname, t.Availability, t.Boostertypes, t.Bordercolor, t.Coloridentity, t.Colors, t.Edhrecsaltiness, t.Facename, t.Finishes, t.Flavorname, t.Flavortext, t.Frameeffects, t.Frameversion, t.Hasfoil, t.Hasnonfoil, t.Isfullart, t.Isfunny, t.Isoversized, t.Ispromo, t.Isreprint, t.Istextless, t.Keywords, t.Language, t.Layout, t.Manacost, t.Name, t.Number, t.Orientation, t.Originaltext, t.Otherfaceids, t.Power, t.Promotypes, t.Relatedcards, t.Reverserelated, t.Securitystamp, t.Setcode, t.Side, t.Signature, t.Subtypes, t.Supertypes, t.Text, t.Toughness, t.Type, t.Types, t.UUID, t.Watermark).Scan(&t.ID); err != nil {
		return logerror(err)
	}
	// set exists
	t._exists = true
	return nil
}

// Update updates a [Token] in the database.
func (t *Token) Update(ctx context.Context, db DB) error {
	switch {
	case !t._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case t._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.tokens SET ` +
		`artist = $1, artistids = $2, asciiname = $3, availability = $4, boostertypes = $5, bordercolor = $6, coloridentity = $7, colors = $8, edhrecsaltiness = $9, facename = $10, finishes = $11, flavorname = $12, flavortext = $13, frameeffects = $14, frameversion = $15, hasfoil = $16, hasnonfoil = $17, isfullart = $18, isfunny = $19, isoversized = $20, ispromo = $21, isreprint = $22, istextless = $23, keywords = $24, language = $25, layout = $26, manacost = $27, name = $28, number = $29, orientation = $30, originaltext = $31, otherfaceids = $32, power = $33, promotypes = $34, relatedcards = $35, reverserelated = $36, securitystamp = $37, setcode = $38, side = $39, signature = $40, subtypes = $41, supertypes = $42, text = $43, toughness = $44, type = $45, types = $46, uuid = $47, watermark = $48 ` +
		`WHERE id = $49`
	// run
	logf(sqlstr, t.Artist, t.Artistids, t.Asciiname, t.Availability, t.Boostertypes, t.Bordercolor, t.Coloridentity, t.Colors, t.Edhrecsaltiness, t.Facename, t.Finishes, t.Flavorname, t.Flavortext, t.Frameeffects, t.Frameversion, t.Hasfoil, t.Hasnonfoil, t.Isfullart, t.Isfunny, t.Isoversized, t.Ispromo, t.Isreprint, t.Istextless, t.Keywords, t.Language, t.Layout, t.Manacost, t.Name, t.Number, t.Orientation, t.Originaltext, t.Otherfaceids, t.Power, t.Promotypes, t.Relatedcards, t.Reverserelated, t.Securitystamp, t.Setcode, t.Side, t.Signature, t.Subtypes, t.Supertypes, t.Text, t.Toughness, t.Type, t.Types, t.UUID, t.Watermark, t.ID)
	if _, err := db.ExecContext(ctx, sqlstr, t.Artist, t.Artistids, t.Asciiname, t.Availability, t.Boostertypes, t.Bordercolor, t.Coloridentity, t.Colors, t.Edhrecsaltiness, t.Facename, t.Finishes, t.Flavorname, t.Flavortext, t.Frameeffects, t.Frameversion, t.Hasfoil, t.Hasnonfoil, t.Isfullart, t.Isfunny, t.Isoversized, t.Ispromo, t.Isreprint, t.Istextless, t.Keywords, t.Language, t.Layout, t.Manacost, t.Name, t.Number, t.Orientation, t.Originaltext, t.Otherfaceids, t.Power, t.Promotypes, t.Relatedcards, t.Reverserelated, t.Securitystamp, t.Setcode, t.Side, t.Signature, t.Subtypes, t.Supertypes, t.Text, t.Toughness, t.Type, t.Types, t.UUID, t.Watermark, t.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Token] to the database.
func (t *Token) Save(ctx context.Context, db DB) error {
	if t.Exists() {
		return t.Update(ctx, db)
	}
	return t.Insert(ctx, db)
}

// Upsert performs an upsert for [Token].
func (t *Token) Upsert(ctx context.Context, db DB) error {
	switch {
	case t._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.tokens (` +
		`id, artist, artistids, asciiname, availability, boostertypes, bordercolor, coloridentity, colors, edhrecsaltiness, facename, finishes, flavorname, flavortext, frameeffects, frameversion, hasfoil, hasnonfoil, isfullart, isfunny, isoversized, ispromo, isreprint, istextless, keywords, language, layout, manacost, name, number, orientation, originaltext, otherfaceids, power, promotypes, relatedcards, reverserelated, securitystamp, setcode, side, signature, subtypes, supertypes, text, toughness, type, types, uuid, watermark` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`artist = EXCLUDED.artist, artistids = EXCLUDED.artistids, asciiname = EXCLUDED.asciiname, availability = EXCLUDED.availability, boostertypes = EXCLUDED.boostertypes, bordercolor = EXCLUDED.bordercolor, coloridentity = EXCLUDED.coloridentity, colors = EXCLUDED.colors, edhrecsaltiness = EXCLUDED.edhrecsaltiness, facename = EXCLUDED.facename, finishes = EXCLUDED.finishes, flavorname = EXCLUDED.flavorname, flavortext = EXCLUDED.flavortext, frameeffects = EXCLUDED.frameeffects, frameversion = EXCLUDED.frameversion, hasfoil = EXCLUDED.hasfoil, hasnonfoil = EXCLUDED.hasnonfoil, isfullart = EXCLUDED.isfullart, isfunny = EXCLUDED.isfunny, isoversized = EXCLUDED.isoversized, ispromo = EXCLUDED.ispromo, isreprint = EXCLUDED.isreprint, istextless = EXCLUDED.istextless, keywords = EXCLUDED.keywords, language = EXCLUDED.language, layout = EXCLUDED.layout, manacost = EXCLUDED.manacost, name = EXCLUDED.name, number = EXCLUDED.number, orientation = EXCLUDED.orientation, originaltext = EXCLUDED.originaltext, otherfaceids = EXCLUDED.otherfaceids, power = EXCLUDED.power, promotypes = EXCLUDED.promotypes, relatedcards = EXCLUDED.relatedcards, reverserelated = EXCLUDED.reverserelated, securitystamp = EXCLUDED.securitystamp, setcode = EXCLUDED.setcode, side = EXCLUDED.side, signature = EXCLUDED.signature, subtypes = EXCLUDED.subtypes, supertypes = EXCLUDED.supertypes, text = EXCLUDED.text, toughness = EXCLUDED.toughness, type = EXCLUDED.type, types = EXCLUDED.types, uuid = EXCLUDED.uuid, watermark = EXCLUDED.watermark `
	// run
	logf(sqlstr, t.ID, t.Artist, t.Artistids, t.Asciiname, t.Availability, t.Boostertypes, t.Bordercolor, t.Coloridentity, t.Colors, t.Edhrecsaltiness, t.Facename, t.Finishes, t.Flavorname, t.Flavortext, t.Frameeffects, t.Frameversion, t.Hasfoil, t.Hasnonfoil, t.Isfullart, t.Isfunny, t.Isoversized, t.Ispromo, t.Isreprint, t.Istextless, t.Keywords, t.Language, t.Layout, t.Manacost, t.Name, t.Number, t.Orientation, t.Originaltext, t.Otherfaceids, t.Power, t.Promotypes, t.Relatedcards, t.Reverserelated, t.Securitystamp, t.Setcode, t.Side, t.Signature, t.Subtypes, t.Supertypes, t.Text, t.Toughness, t.Type, t.Types, t.UUID, t.Watermark)
	if _, err := db.ExecContext(ctx, sqlstr, t.ID, t.Artist, t.Artistids, t.Asciiname, t.Availability, t.Boostertypes, t.Bordercolor, t.Coloridentity, t.Colors, t.Edhrecsaltiness, t.Facename, t.Finishes, t.Flavorname, t.Flavortext, t.Frameeffects, t.Frameversion, t.Hasfoil, t.Hasnonfoil, t.Isfullart, t.Isfunny, t.Isoversized, t.Ispromo, t.Isreprint, t.Istextless, t.Keywords, t.Language, t.Layout, t.Manacost, t.Name, t.Number, t.Orientation, t.Originaltext, t.Otherfaceids, t.Power, t.Promotypes, t.Relatedcards, t.Reverserelated, t.Securitystamp, t.Setcode, t.Side, t.Signature, t.Subtypes, t.Supertypes, t.Text, t.Toughness, t.Type, t.Types, t.UUID, t.Watermark); err != nil {
		return logerror(err)
	}
	// set exists
	t._exists = true
	return nil
}

// Delete deletes the [Token] from the database.
func (t *Token) Delete(ctx context.Context, db DB) error {
	switch {
	case !t._exists: // doesn't exist
		return nil
	case t._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.tokens ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, t.ID)
	if _, err := db.ExecContext(ctx, sqlstr, t.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	t._deleted = true
	return nil
}

// TokenByID retrieves a row from 'public.tokens' as a [Token].
//
// Generated from index 'tokens_pkey'.
func TokenByID(ctx context.Context, db DB, id int) (*Token, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, artist, artistids, asciiname, availability, boostertypes, bordercolor, coloridentity, colors, edhrecsaltiness, facename, finishes, flavorname, flavortext, frameeffects, frameversion, hasfoil, hasnonfoil, isfullart, isfunny, isoversized, ispromo, isreprint, istextless, keywords, language, layout, manacost, name, number, orientation, originaltext, otherfaceids, power, promotypes, relatedcards, reverserelated, securitystamp, setcode, side, signature, subtypes, supertypes, text, toughness, type, types, uuid, watermark ` +
		`FROM public.tokens ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	t := Token{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&t.ID, &t.Artist, &t.Artistids, &t.Asciiname, &t.Availability, &t.Boostertypes, &t.Bordercolor, &t.Coloridentity, &t.Colors, &t.Edhrecsaltiness, &t.Facename, &t.Finishes, &t.Flavorname, &t.Flavortext, &t.Frameeffects, &t.Frameversion, &t.Hasfoil, &t.Hasnonfoil, &t.Isfullart, &t.Isfunny, &t.Isoversized, &t.Ispromo, &t.Isreprint, &t.Istextless, &t.Keywords, &t.Language, &t.Layout, &t.Manacost, &t.Name, &t.Number, &t.Orientation, &t.Originaltext, &t.Otherfaceids, &t.Power, &t.Promotypes, &t.Relatedcards, &t.Reverserelated, &t.Securitystamp, &t.Setcode, &t.Side, &t.Signature, &t.Subtypes, &t.Supertypes, &t.Text, &t.Toughness, &t.Type, &t.Types, &t.UUID, &t.Watermark); err != nil {
		return nil, logerror(err)
	}
	return &t, nil
}

// TokensByUUID retrieves a row from 'public.tokens' as a [Token].
//
// Generated from index 'tokens_uuid'.
func TokensByUUID(ctx context.Context, db DB, uuid string) ([]*Token, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, artist, artistids, asciiname, availability, boostertypes, bordercolor, coloridentity, colors, edhrecsaltiness, facename, finishes, flavorname, flavortext, frameeffects, frameversion, hasfoil, hasnonfoil, isfullart, isfunny, isoversized, ispromo, isreprint, istextless, keywords, language, layout, manacost, name, number, orientation, originaltext, otherfaceids, power, promotypes, relatedcards, reverserelated, securitystamp, setcode, side, signature, subtypes, supertypes, text, toughness, type, types, uuid, watermark ` +
		`FROM public.tokens ` +
		`WHERE uuid = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Token
	for rows.Next() {
		t := Token{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&t.ID, &t.Artist, &t.Artistids, &t.Asciiname, &t.Availability, &t.Boostertypes, &t.Bordercolor, &t.Coloridentity, &t.Colors, &t.Edhrecsaltiness, &t.Facename, &t.Finishes, &t.Flavorname, &t.Flavortext, &t.Frameeffects, &t.Frameversion, &t.Hasfoil, &t.Hasnonfoil, &t.Isfullart, &t.Isfunny, &t.Isoversized, &t.Ispromo, &t.Isreprint, &t.Istextless, &t.Keywords, &t.Language, &t.Layout, &t.Manacost, &t.Name, &t.Number, &t.Orientation, &t.Originaltext, &t.Otherfaceids, &t.Power, &t.Promotypes, &t.Relatedcards, &t.Reverserelated, &t.Securitystamp, &t.Setcode, &t.Side, &t.Signature, &t.Subtypes, &t.Supertypes, &t.Text, &t.Toughness, &t.Type, &t.Types, &t.UUID, &t.Watermark); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &t)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
